matrix:
  include:
    - os: osx
      osx_image: xcode9.3
      language: objective-c
      sudo: required
script:
  - make test
before_install:
  - chmod ugo+x ./.assets/scripts/InstallSwift.sh
  - . ./.assets/scripts/InstallSwift.sh
notifications:
  email:
    on_success: never
    on_failure: change
