#!/usr/bin/env bash

_hazel_complete() {
  COMPREPLY=()
  local word="${COMP_WORDS[COMP_CWORD]}"
  local line=(${COMP_WORDS[@]})
	line=(${COMP_WORDS[@]})
	line[0]=""
	if [ ${#line[@]} -gt 1 ]
	then
		line=(${line[@]}:1)
	fi

  local completions="$(hazel cmplt-bash "${line[@]}")"
  COMPREPLY=( $(compgen -W "$completions" -- "$word") )
}

complete -F _hazel_complete hazel
